# Site settings
title: "Thorsten D. Gawantka"
description: "Mein Lebenslauf"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Thorsten D. Gawantka"
resume_title:                   "Software Architekt und Senior Consultant"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "t.gawantka+resume@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+49 151 56 963 191"
resume_contact_address:         "Körnerstraße 10/3, 69469 Weinheim"

resume_header_contact_info:     "Körnerstraße 10/3, 69469 Weinheim • +49 151 56 963 191 • t.gawantka+resume@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Ich bin Software Architekt, Lead Developer und Trainer rund um AWS, SAP Cloud Plattform, Java / EE und Spring, TypeScript und Angular.</p><p>Meine Zuverlässigkeit und Belastbarkeit sowie Flexibilität zeichnen mich aus.</p><p>Als echter Teamplayer füge ich mich schnell in neue Teams und Projekte ein.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/thogaw"
  resume_twitter_url:           "https://twitter.com/TGawantka"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/thorsten-gawantka-0b9129a8/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
